<?php 
        // user \dclass\devups\model\Model;
    /**
     * @Entity @Table(name="sessionpaiement")
     * */
    class Sessionpaiement extends Model implements JsonSerializable{

        /**
         * @Id @GeneratedValue @Column(type="integer")
         * @var int
         * */
        protected $id;
        /**
         * @Column(name="datedebut", type="datetime" , nullable=true )
         * @var datetime
         **/
        protected $datedebut;
        /**
         * @Column(name="datefin", type="datetime" , nullable=true )
         * @var datetime
         **/
        protected $datefin;
        /**
         * @Column(name="name", type="string" , length=255, nullable=true )
         * @var string
         **/
        protected $name;
        /**
         * @Column(name="numero", type="integer" , nullable=true )
         * @var integer
         **/
        protected $numero = 0;

        /**
         * @Column(name="statut", type="integer" , nullable=true )
         * @var integer
         **/
        protected $statut =0 ;




        /**
         * @Column(name="pourcentagegain", type="integer" , nullable=true )
         * @var integer
         **/
//Cette valeur par defaut ne devra pas etre changé faute de quoi les données datant de 2022 auront des problemes d integrite de données
        protected $pourcentagegain =10;



        public function __construct($id = null){
            
                if( $id ) { $this->id = $id; }   
                          
}

        public function getId() {
            return $this->id;
        }
        public function getDatedebut() {
            return $this->datedebut;
        }

        public function setDatedebut($datedebut) {
            $this->datedebut = $datedebut;
        }
        
        public function getDatefin() {
            return $this->datefin;
        }

        public function setDatefin($datefin) {
            $this->datefin = $datefin;
        }
        
        public function getName() {
            return $this->name;
        }

        public function setName($name) {
            $this->name = $name;
        }
        
        public function getNumero() {
            return $this->numero;
        }

        public function setNumero($numero) {
            $this->numero = $numero;
        }

        /**
         * @return int
         */
        public function getStatut()
        {
            return $this->statut;
        }

        /**
         * @param int $statut
         */
        public function setStatut($statut)
        {
            $this->statut = $statut;
        }

        public function getSatutName(){
            if($this->statut == 0)
                return tt('En cours');
            else
                return tt('termine');
        }

        /**
         * @return int
         */
        public function getPourcentagegain()
        {
            return $this->pourcentagegain;
        }

        /**
         * @param int $pourcentagegain
         */
        public function setPourcentagegain($pourcentagegain)
        {
            $this->pourcentagegain = $pourcentagegain;
        }


        
        
        public function jsonSerialize() {
                return [
                    'id' => $this->id,
                    'datedebut' => $this->datedebut,
                    'datefin' => $this->datefin,
                    'name' => $this->name,
                    'numero' => $this->numero,
                ];
        }

        public function __insert()
        {
            $numero = 0;
            $sessions = array_reverse(Sessionpaiement::all());
            if(count($sessions) >0){
                $lastsession =$sessions[0];
                $numero = $lastsession->getNumero();
                $lastsession->setDatefin(date('Y-m-d H:i:s'));
                $lastsession->setStatut(1);
                $lastsession->__update();
            }

            $numero++;
            $this->setNumero($numero);
            $this->setName('Session'.$numero);
            $this->setDatedebut(date('Y-m-d H:i:s'));
            $this->setStatut(0);
            $id = parent::__insert();

            $sessioncodepromo = new Sessioncodepromo();
            $sessioncodepromo->setIspacekola(1);
            $sessioncodepromo->setSessionpaiement(self::find($id));
            $sessioncodepromo->__insert();
            return $id; // TODO: Change the autogenerated stub
        }
        
}
