<?php 
        // user \dclass\devups\model\Model;
    /**
     * @Entity @Table(name="codepromosubscription")
     * */
    class Codepromosubscription extends Model implements JsonSerializable{

        /**
         * @Id @GeneratedValue @Column(type="integer")
         * @var int
         * */
        protected $id; 
        
        /**
         * @ManyToOne(targetEntity="\Subscription")
         * @JoinColumn(onDelete="cascade")
         * @var \Subscription
         */
        public $subscription;

        /**
         * @ManyToOne(targetEntity="\Codepromo")
         * @JoinColumn(onDelete="cascade")
         * @var \Codepromo
         */
        public $codepromo;

        /**
         * @Column(name="paypalproduct", type="string" , length=255 , nullable=true)
         * @var string
         **/
        protected $paypalproduct;

        /**
         * @Column(name="paypalplan", type="string" , length=255 , nullable=true)
         * @var string
         **/
        protected $paypalplan;


        
        public function __construct($id = null){
            
                if( $id ) { $this->id = $id; }   
                          
	$this->subscription = new Subscription();
	$this->codepromo = new Codepromo();
}

        public function getId() {
            return $this->id;
        }
        /**
         *  manyToOne
         *	@return \Subscription
         */
        function getSubscription() {
            $this->subscription = $this->subscription->__show();
            return $this->subscription;
        }
        function setSubscription(\Subscription $subscription) {
            $this->subscription = $subscription;
        }
                        
        /**
         *  manyToOne
         *	@return \Codepromo
         */
        function getCodepromo() {
            $this->codepromo = $this->codepromo->__show();
            return $this->codepromo;
        }
        function setCodepromo(\Codepromo $codepromo) {
            $this->codepromo = $codepromo;
        }

        /**
         * @return string
         */
        public function getPaypalproduct()
        {
            return $this->paypalproduct;
        }

        /**
         * @param string $paypalproduct
         */
        public function setPaypalproduct($paypalproduct)
        {
            $this->paypalproduct = $paypalproduct;
        }

        /**
         * @return string
         */
        public function getPaypalplan()
        {
            return $this->paypalplan;
        }

        /**
         * @param string $paypalplan
         */
        public function setPaypalplan($paypalplan)
        {
            $this->paypalplan = $paypalplan;
        }


                        
        
        public function jsonSerialize() {
                return [
                    'id' => $this->id,
                    'subscription' => $this->subscription,
                    'codepromo' => $this->codepromo,
                    'paypalproductid' => $this->paypalproduct,
                    'paypalplan' => $this->paypalplan,
                ];
        }

        public function __insert()
        {
            $percentpromo = $this->getCodepromo()->getValeur();
            $access_token = $this->getSubscription()->generateTokken();
            $paypalproductid = $this->getSubscription()->generatePaypalproduct($access_token);
            $this->setPaypalproduct($paypalproductid);

    

            $paypalplan = $this->getSubscription()->generatePaypalplan($access_token,'MONTH',$paypalproductid,$percentpromo,true);

//            var_dump($paypalplan);

            $this->setPaypalplan($paypalplan);
            return parent::__insert(); // TODO: Change the autogenerated stub
        }

    }
